name: Build & Test
run-name: Build & Test multi

on: 
    workflow_dispatch:
        inputs:
            something:
                required: true
                default: ajkaj
    push:
        branches:
                - main


env:
    BUILD_TYPE: Debug

jobs:
    build-and-test:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]



        runs-on: ${{matrix.os}}

        steps:
            - uses: actions/checkout@v4 # dont use action/checkout@main main branch could possibly change 

            - name: Configure CMake
              run: cmake  -B build/ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST=ON

            - name: Build Project
              run: cmake --build build/ --config ${{env.BUILD_TYPE}}

            - name: Run Tests
              run: ctest --test-dir build/