name: Issue Greeter

on:
    issues:
        types: [opened]

permissions:
    issues: write
    contents: read
    
    

jobs:
    greet-bash:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run greeter Action (Bash)
              uses: ./.github/actions/issue-greeter-action-bash 
              with:
                issue-url: ${{github.event.issue.url}}
                comment-body: "Hi $${{github.actor}}, thanks for opening! We'll get your order soon"
                token: ${{secrets.GITHUB_TOKEN}}